title: Furong's Note
description: 记录一些工作中遇到的技术问题

url: https://lfrmm.github.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: 首页
   url: /index.html
 - title: 关于我
   url: /about

social:
   github: lfrmm
   twitter: 
   facebook: 
   email: lfrmm18622@gmail.com

google_analytics: "UA-582634161-1"
